### PR TITLE
Add Montenegrin language translation

### PR DESCRIPTION
**Pull request by milose**

### CODE REVIEW

**Comment by lucasmichot** [comment]
thanks a lot @milose 
Can you also add tests ?

**Comment by milose** [comment]
Phew, thanks for reminding me to do tests. Pluralisation for Montenegrin is such a pain.

**Comment by milose** [comment]
I am baffled by this. There is no language code defined by https://www.iso.org/obp/ui/#iso:code:3166:ME and `ME` is **only** a country code.

However, according to http://symbolcodes.tlt.psu.edu/bylanguage/serbocroatian.html website, there are three variants for this locale:
- `sr-ME` (Montenegrin, script unspecified)
- `sr-Cyrl-ME` (Montenegrin in Cyrillic)
- `sr-Latn-ME` (Montenegrin in Latin Script)

This reflects the situation in real life, as both scripts (Latin and Cyrilic) are used in Montenegrin language.

Specifically, in this PR, Montenegrin language is translated in Latin script. So if someone is building a Cyrilic script website and used this translation they would end up with mixed scripts on their page.

I will make another PR that would allow `Carbon::setLocale` to accept `ll-Ssss-RR` format to be passed, and if merged, I would update this PR to reflect that. On top of that I would add a translation using Cyrilic script as well.

**Comment by lucasmichot** [comment]
https://github.com/briannesbitt/Carbon/pull/825 was just merged @milose 
Does this PR needs adjustments ?

**Comment by lucasmichot** [comment]
@milose we are planning to make a new release after your PR is merged

**Comment by milose** [comment]
@lucasmichot I will add test for Cyrillic soon and then you can merge it.

**Comment by milose** [comment]
@lucasmichot All done.

**Pull request merged**
