### PR TITLE
Hungarian translation improved A LOT

### PR DESCRIPTION
**Pull request by balping**
... after I realised that actually I can use second_before, second_ago, etc keys.
Reading the original source code can be really useful!

Also, unit test added for Hungarian language

### CODE REVIEW

**Comment by balping** [comment]
StyleCI formatting corrected

**Comment by GrahamCampbell** [comment]
> StyleCI formatting corrected

Not exactly.

**Comment by dereuromark** [comment]
Just some minor whitespace: https://styleci.io/analyses/qoaeZ8
@balping Always keep your "trim right" option of your IDE enabled to prevent this.

**Comment by balping** [comment]
Nah, finally StyleCI has passed

@dereuromark Thanks for the suggestion

**Comment by lucasmichot** [comment]
Great work @balping !
Yeah lots of changes, this is what I was suspecting... I am a bit skeptical about the qualities of other translations files BTW, I've been checking fr/he/de files which are OK, but your PR is a good indicator of issues of untested and mostly imported language files.

**Comment by balping** [comment]
Thanks @lucasmichot  !

Yeah, I was working on my own projects when I realized that in many cases the printed text made actually no sense. Maybe that's the case with other translations of smaller languages as well

**Pull request merged**
