### PR TITLE
Fix floating point modulo in floatDiffInDays() when $hoursDiff is a float

### PR DESCRIPTION
**Pull request by pflueg**
Hi there!

I experienced an issue in the Carbon\Traits\Difference::floatDiffInDays() function when the used function floatDiffInHours() is returning a decimal part.

Carbon is using the modulo operand directly. Unfortunately PHP is stripping any decimal parts beforehand and is using the numbers only as real integers:

```
php > $hoursDiff = 48.13;
php > var_dump($hoursDiff % 24);
int(0)
```

For floating-point modulo the library needs to use the php function [fmod()](https://www.php.net/manual/en/function.fmod.php).

```
php > $hoursDiff = 48.13;
php > var_dump(fmod($hoursDiff, 24));
float(0.13)
```

In this PR i changed it, added a case to the unittests and adapted all expected values in the other assertions, that are now using the decimal part as well

Cheers o/

### CODE REVIEW

**Comment by kylekatarnls** [comment]
Thanks for your help, it seems correct. I will compare precision after/before to be sure and check where else we use modulo. It could be in the next minor release.

**Comment by pflueg** [comment]
@kylekatarnls : Do you already know when the next version is going to be released with this fix in it?

**Comment by kylekatarnls** [comment]
Before the end of the week. Now that Carbon is stable enough, I plan to release 1 minor version per month on Carbon 2.x.
https://github.com/briannesbitt/Carbon/issues/1681

**Comment by kylekatarnls** [comment]
2.17.0 released.

**Pull request merged**
