### PR TITLE
Simplify calls to parent functions

### PR DESCRIPTION
**Pull request by lucasmichot**
Simplify calls to parent functions

### CODE REVIEW

**Comment by dereuromark** [comment]
The actual code coverage is probably more around 97%
The lang files should probably not count in too much :)

**Comment by lucasmichot** [comment]
Indeed @dereuromark / currently looking at the codecov settings to fix that ;-)

**Comment by lucasmichot** [comment]
But weel in facts, the localizations should be covered !!!! :-D
Which is not the case for most of them ATM

**Comment by lucasmichot** [comment]
@dereuromark you were real close ;-) : 98.23 %
https://github.com/briannesbitt/Carbon/pull/501#issuecomment-155408089

**Comment by dereuromark** [comment]
@lucasmichot Well, I got my number from https://coveralls.io/github/cakephp/chronos which is pretty much 100% API-consistent.

**Pull request merged**
