### PR TITLE
[AR] Update with enhancements

### PR DESCRIPTION
**Pull request by mohamedsabil83**
- Syncing with main file.
- Update translation for both missing and needed text.

### CODE REVIEW

**Comment by mohamedsabil83** [comment]
I'll try to change it from `]#,#[ ` to `a|b|c` and check it again.

**Comment by mohamedsabil83** [comment]
After reviewing all Arabic files and their units test, I just figured all the problems and fix them all

**Comment by kylekatarnls** [comment]
Thanks a lot. I started to do some random checks and seem good. I will recheck for `a|b|c` syntax and merge this.

**Comment by mohamedsabil83** [comment]
Y.W. I do my check also before the last commit and it works either using `]#,#[` or `a|b|c`
Waiting for merge after completing your test.

**Comment by kylekatarnls** [comment]
Thank you. It will be in 2.24.0

**Pull request merged**
