### PR TITLE
Speed up resetMessages

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Before:

image

After:

image

### CODE REVIEW

**Comment by kylekatarnls** [comment]
Thanks, good idea. I will check why Travis fails.

**Comment by kylekatarnls** [comment]
Hi @GrahamCampbell it fails because using `require` on non-existing file exit the processus. Would the performance remain the same using `include`?

**Comment by GrahamCampbell** [comment]
Yeh, should be fine.

**Comment by kylekatarnls** [comment]
This improvement + preloading feature (of OPCache for PHP 7.4) + requiring favorite languages files in the preloading script should improve significantly the Carbon loading in Laravel boot.

**Comment by GrahamCampbell** [comment]
Though, I don't think preloading is capable of pre-processing conditional includes.

**Comment by kylekatarnls** [comment]
I'm basically suggesting when developing an app (a Laravel app for instance), you can add a preloading script:
```php
// Include all from composer classmap optimized autoload

require __DIR__.'/vendor/nesbot/carbon/src/Carbon/Lang/en.php';
```
Assuming the app only use English for instance, so **en.php** is preloaded and the boot of the app should load even faster as en.php would already be in memory, so if I well understand the preloading feature `$data = @include sprintf('%s/%s.php', rtrim($directory, '\\/'), $locale);` should not actually access the file if `$locale` is `"en"`.

**Comment by GrahamCampbell** [comment]
Well, the opcache system will already do this?

**Comment by kylekatarnls** [comment]
Not an expert of this feature, but what I understood is: OPCache will cache the file the first time it's loaded (so slower the first time), then check if the file changed and use cache if not changed for other loadings (faster).

With the preloading script, you can also fasten the first loading.

Bonus: you can clear cache on deploy to disable also the change checking. AFAIK this can be done with or without the preloading script.

**Comment by GrahamCampbell** [comment]
Yeh, that's right.

**Comment by kylekatarnls** [comment]
Thank you very much for your help, it will be released in 2.29.0.

**Pull request merged**
