### PR TITLE
Added composer branch alias

### PR DESCRIPTION
**Pull request by martinssipenko**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
Should include the minor version too.

**Comment by martinssipenko** [comment]
would this work?

**Comment by GrahamCampbell** [comment]
Yes and no.

**Comment by GrahamCampbell** [comment]
Works, but should probably be `1.22-dev`.

**Comment by martinssipenko** [comment]
Fixed. @GrahamCampbell thanks for input, much appreciated!

**Pull request merged**
