### PR TITLE
Use the native way to get today/yesterday/tomorrow

### PR DESCRIPTION
**Pull request by kylekatarnls**
Can fix problem like this one: #1187

### CODE REVIEW

**Comment by halloei** [comment]
Does not fix the issue with `startOfDay()`.

**Comment by kylekatarnls** [comment]
No it has nothing to do with `startOfDay()`. When doing `startOfDay()` on a date with microseconds, microseconds will not be removed, it's not our fault, PHP 7.0 just does not allow to modify microseconds and `startOfDay` must be compatible from 5.3 to 7.2, the best we could do would be to remove microseconds  in startOfDay only for PHP >= 7.1.

Nevertheless, this PR allows to have proper microseconds to 0 when calling `today()`, `yesterday()` and `tomorrow()` and you said you used `today()`.

**Comment by kylekatarnls** [comment]
If you have a better solution, please do not hesitate to propose your own.

**Comment by halloei** [comment]
You're aware of the fact that before PHP 7.1, modifying microseconds is not fully supported. So why did you have to implement Carbon support for microseconds for those PHP versions? Espacially when Carbon 2 is about to be released.
You've released a breaking change as minor version. My solution would be to revert those commits and release them under a new major version.

**Comment by kylekatarnls** [comment]
Sorry, we won't do that, consider replacing a false data (microsecond = 0) by a data not accurate in all cases as a breaking change is questionable (note that we're largely covered by tests and none of documented usages broke after this change), but removing a feature surely is a BC and removing it can bother a lot more people.

I will merge this PR since it fixes #1189.

I also propose to to enable/disable the µs adding with some method like `Carbon::useMicrosecondsFallback()`. It will not be prior on other stuff for 1.25 but if you're interested to do a PR for that, I would merge it.

Thanks for your feedback.

**Comment by kylekatarnls** [comment]
You will be able to disable this feature on 1.25 thanks to #1197

**Pull request merged**
