### PR TITLE
Added Georgian (ka) localization

### PR DESCRIPTION
**Pull request by akalongman**
Added Georgian (ka) localization. Also included unit tests

### CODE REVIEW

**Comment by tatocaster** [comment]
:+1:  @akalongman

**Comment by akalongman** [comment]
@briannesbitt what about this PR? We want use lib in production and ka localization is needed

**Comment by akalongman** [comment]
@briannesbitt thank you for merging. When will be released new version with this PR?

**Comment by tatocaster** [comment]
@briannesbitt  When this PR will be available in production?

**Comment by akalongman** [comment]
@briannesbitt please release version with this PR

**Comment by akalongman** [comment]
@briannesbitt up

**Comment by briannesbitt** [comment]
Heading to a release soonish

**Pull request merged**
