### PR TITLE
Extra helpers and code coverage

### PR DESCRIPTION
**Pull request by EGYG33K**
* Document enhancement and corrections
* Unit test coverage higher percentage
* New functionalities
 * birthYear($age): int year of birth
 * age($dateOfBirth): array $ageArray age in years,months,days,hours,minutes and seconds
 * ageForHumans($dateOfBirth): string $ageString age in years,months,days,hours,minutes and seconds human readable
 * ageInDays($dateOfBirth): int age in days
 * ageInHours($dateOfBirth): int age in hours
 * ageInMinutes($dateOfBirth): int age in minutes
 * toArray(): array
 * startOfHour(): Carbon Modify to start of current hour, minutes and seconds become 0
 * endOfHour(): Carbon Modify to end of current hour, minutes and seconds become 59
 * startOfMinute(): Carbon Modify to start of current minute, seconds become 0
 * endOfMinute() : Carbon Modify to end of current minute, seconds become 59
 * midDay(): Carbon Modify to midday, default to self::$midDayAt

### CODE REVIEW

**Comment by lucasmichot** [comment]
@EGYG33K see https://github.com/briannesbitt/Carbon/pull/569#issuecomment-169779925

**Comment by lucasmichot** [comment]
What is this file you have committed `src/Carbon/Carbon.php.original~` ?

**Comment by briannesbitt** [comment]
A lot of this is good, but please break it up into several PR's addressing a single thought at a time.

**Comment by MoaazGouda** [comment]
@EGYG33K

**Pull request closed without merging**
