### PR TITLE
Enable Codecov.io code coverage

### PR DESCRIPTION
**Pull request by lucasmichot**
Enable Codecov.io code coverage

### CODE REVIEW

**Comment by lucasmichot** [comment]
@briannesbitt it's looking like the service has not been enabled on https://codecov.io/ as there not checks on new PR

**Comment by briannesbitt** [comment]
Checking the codecov admin.  Shows code coverage for Carbon repository as a whole and a list of the commits / changes.

I just submitted the config for "Pull Request Comment" so maybe that will do it.  I take it its supposed to submit a comment on new PRs ?

**Comment by lucasmichot** [comment]
This was exactly that !

**Comment by lucasmichot** [comment]
New PR will get the codecov analysis

**Pull request merged**
