### PR TITLE
Add Pashto (PS) Language

### PR DESCRIPTION
**Pull request by mnrafg**

### CODE REVIEW

**Comment by GawainLynch** [comment]
​Owing to the apparently "unmaintained" status of this project (last official update was Februrary 2017), a small group have forked this project, and merged this pull request.
​​
You can safely update to the new project by changing `nesbot/carbon` to `carbondate/carbon` in your project's `composer.json` file.

The new home for the project is https://github.com/CarbonDate/Carbon and we welcome continuing engagement from the open source community.

Please also note that Carbon owes its very existence to Brian Nesbitt's work, and for that, we are eternally grateful.

**Comment by kylekatarnls** [comment]
Hi, Google Translate translate diferrently:
https://translate.google.com/?tl=fa#en/fa/1%20second%20ago

As we can see in the unit test, it seems to be 2 difference:
- The position of 1 in `1ثانيه دمخه`
- The word "ago" you used in translation is recognized by Google Translate as "blade" and it proposes `پیش` instead

Can you provide some sources pleases,

Thanks

**Comment by mnrafg** [comment]
Hi, Mr. Kyle,

The link shared translates between Persian and English, and the translation I provided with this PR is between Pashto and English and you can confirm the words you are concerned about by visiting the links below.

The word ‍‍‍`دمخه` means "before" or "ago": [click here to see the translation by Google Translate](https://translate.google.com/#ps/en/%D8%AF%D9%85%D8%AE%D9%87)
The word `ثانیه` means "second": [click here to see the translation by Google Translate](https://translate.google.com/#ps/en/%D8%AB%D8%A7%D9%86%DB%8C%D9%87)

Thanks,
Nasir

**Comment by kylekatarnls** [comment]
Thanks!

**Pull request merged**
