### PR TITLE
DateTimeInterface implementation with two variations: extension of DateTime and DateTimeImmutable.

### PR DESCRIPTION
**Pull request by jan-j**
Original Carbon class is broken into CarbonInterface (interface extending DateTimeInterface) and CarbonTrait that implements that interface. There are 2 usable classes Carbon extending DateTime (that has exactly the same functionality as original Carbon class) and CarbonImmutable extending DateTimeImmutable. Both classes implement CarbonInterface and use CarbonTrait for common methods.

Backwards compatibility is kept, but only for versions of PHP greater than or equal to 5.5.0. Earlier versions are unsupported, because of DateTimeInterface and DateTimeImmutable, which were introduced in PHP 5.5 unfortunately. All original tests for mutable version of Carbon are passed.

This is only proposal and I know it needs to be discussed thoroughly.

For other info see issue #406.

### CODE REVIEW

**Comment by briannesbitt** [comment]
The general idea here is good but needs to obviously be in a v2.

**Comment by morloderex** [comment]
Any new regarding this?

**Comment by IonutBajescu** [comment]
@briannesbitt there doesn't seem to be any breaking change at first sight though. Wouldn't that warrant a minor version bump at most?

**Comment by jan-j** [comment]
@IonutBajescu It does use DateTimeInterface and DateTimeImmutable which is supported from PHP version 5.5.0 and it is breaking change if someone is using lower version. Although without strictly following semver, only minor version bump is not that terrible idea. Extra constraint can be added for PHP version to composer.json file to make sure, it's not going to be installed on lower versions silently.

**Comment by kylekatarnls** [comment]
Thanks, it will be done with traits to avoid duplicate code.

Fixed via #1315

**Pull request closed without merging**
