### PR TITLE
Improve arabic translation

### PR DESCRIPTION
**Pull request by atefBB**

### CODE REVIEW

**Comment by kylekatarnls** [comment]
Hi @atefBB can you bring some official reference where we can see those formulas?

**Comment by atefBB** [comment]
Hi @kylekatarnls. What did you mean by "official reference"?

**Comment by kylekatarnls** [comment]
A known newspaper, an arabic government website or a linguistic website.

**Comment by kylekatarnls** [comment]
Hi @atefBB I'm sorry but I can't merge this as is. My level in Arabic is insufficient to determine if this is really an improvement. As Arabic can change a lot from country to country, I do not want to merge a change unless this change is documented with well-known references.

**Comment by atefBB** [comment]
I'll see a reference !
Thanks.

**Pull request closed without merging**
