### PR TITLE
Fix arabic translation

### PR DESCRIPTION
**Pull request by MLTDev**
Add missing ":count" to [3,10]  plurals. Correct week translation.

### CODE REVIEW

**Comment by ibrasho** [comment]
I would disagree that `إسبوع` is the correct translation. 
I'm pretty sure that it with a damma and not a kasra.

Can provide any source that backup this claim?

**Comment by ibrasho** [comment]
I've extracted the addition of counts to a separate PR: https://github.com/briannesbitt/Carbon/pull/408

**Comment by ibrasho** [comment]
I would reference as sources https://ar.wikipedia.org/wiki/%D8%A3%D8%B3%D8%A8%D9%88%D8%B9 and http://baheth.info/all.jsp?term=%D8%A5%D8%B3%D8%A8%D9%88%D8%B9.

**Comment by ibrasho** [comment]
This have actually reverted #408 which had the correct translation...

**Comment by briannesbitt** [comment]
Sorry.  Editing the lang files are somewhat problematic when I don't speak the language... ie. all of them !  If you send a PR to fix it I'll merge it.

**Pull request merged**
