### PR TITLE
Add Serbian (Cyrillic) Language

### PR DESCRIPTION
**Pull request by zeravcic**
Script: Cyrl;
Native: Српски;
Regional: sr_RS;

Primary Serbian:
 - Latin: src\Carbon\Lang\sr.php
 - Cyrillic: src\Carbon\Lang\sr_Cyrl.php (this pull request)

About "sr_*ME.php" files: https://sr.wikipedia.org/sr/%D0%98%D1%98%D0%B5%D0%BA%D0%B0%D0%B2%D1%81%D0%BA%D0%B8_%D0%B8%D0%B7%D0%B3%D0%BE%D0%B2%D0%BE%D1%80

### CODE REVIEW

**Comment by Glavic** [comment]
@zeravcic: zdravo :)

Why is _ME version not ok? https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/sr_Cyrl_ME.php

**Comment by zeravcic** [comment]
@Glavic zdravo! :)

I beleve that _ME version is OK.
But, there is another most popular pronounce of the word, based of majority of Serbian population which using it.

So, this pull request just add new file for 'sr_Cyrl' pronounce of the word.

**Comment by Glavic** [comment]
Ahh, I understand now :) You wish to add `ekavica` instead of already added `ljekavica`. That would be a nice feature. But we would also need ekavica for latinica. And then all the tests for all the combinations.

**Comment by zeravcic** [comment]
@Glavic that already exists on [src/Carbon/Lang/sr.php](https://github.com/briannesbitt/Carbon/blob/1.22.1/src/Carbon/Lang/sr.php)

Maybe only to improve that file for non-existing elements?
```
+    'year_from_now' => '{1,21,31,41,51} :count godinu|{2,3,4,22,23,24,32,33,34,42,43,44,52,53,54} :count godine|[5,Inf[ :count godina',
+    'year_ago' => '{1,21,31,41,51} :count godinu|{2,3,4,22,23,24,32,33,34,42,43,44,52,53,54} :count godine|[5,Inf[ :count godina',
+
+    'week_from_now' => '{1} :count nedelju|{2,3,4} :count nedelje|[5,Inf[ :count nedelja',
+    'week_ago' => '{1} :count nedelju|{2,3,4} :count nedelje|[5,Inf[ :count nedelja',
```

**Comment by kylekatarnls** [comment]
Hi, do we are OK we should merge a new sr_Cyrl.php file but just fix existing files: Mj. => M. in sr_Cyrl_ME.php and add 4 missing keys in sr.php?

If so would you be OK to edit your PR (or create a new one) with those changes?

**Pull request merged**
