### PR TITLE
fix before & after pl language

### PR DESCRIPTION
**Pull request by pderiy**

### CODE REVIEW

**Comment by GawainLynch** [comment]
​Owing to the apparently "unmaintained" status of this project (last official update was Februrary 2017), a small group have forked this project, and merged this pull request.
​​
You can safely update to the new project by changing `nesbot/carbon` to `carbondate/carbon` in your project's `composer.json` file.

The new home for the project is https://github.com/CarbonDate/Carbon and we welcome continuing engagement from the open source community.

Please also note that Carbon owes its very existence to Brian Nesbitt's work, and for that, we are eternally grateful.

**Comment by Glavic** [comment]
@pderiy: could you do rebase? 
+ maybe write test for polish language?

**Comment by pderiy** [comment]
@Glavic no, because I'm using CarbonDate. It's like half year

**Comment by Glavic** [comment]
@pderiy: better ever than never :) I wish you all the well.

**Comment by kylekatarnls** [comment]
Fixed via #1065

**Comment by pderiy** [comment]
@kylekatarnls Oh, there is no tests 🙂

**Comment by kylekatarnls** [comment]
Yes, for several languages. I'm writing them.

**Comment by kylekatarnls** [comment]
Hi @pderiy please accept our apologize, we're new maintainers and there are a lot of PRs to check. It would have been legit to merge yours.  It already happened to me to send PR and see the same PR later merged. I know it can be frustrating. We'll do our best to be fair and check more carefully. We hope you will not be discouraged to contribute.

**Pull request closed without merging**
