### PR TITLE
Fix #1740 Czech translation

### LINKED ISSUE #1740: [Translation tool] cs_CZ
|English|cs_CZ|comments|
|--|--|--|
|a month|1 měsíc|měsíc|
|a week|1 týden|týden|
|a day|1 den|den|
|1 hour|1 hodinu|1 hodina|
|an hour|1 hodinu|hodina|
|1 minute|1 minutu|1 minuta|
|a minute|1 minutu|minuta|
|1 second|1 sekundu|1 sekunda|
|a few seconds|1 sekundu|pár sekund|
|Jun|čer|čvn|
|Jul|čer|čvc|
|2 hours ago|2 hodiny nazpět|2 hodiny před|
|2 hours before|2 hodiny předtím|2 hodiny před|
|2 hours after|o 2 hodiny později|2 hodiny po|

### PR DESCRIPTION
**Pull request by kylekatarnls**
- Implement a_unit forms
- Fix hodina/hodinu, minuta/minutu, sekunda/sekundu declensions
- Use čvn/čvc to distinguish June from July

### CODE REVIEW

**Comment by kylekatarnls** [comment]
@Tlapi, @Newman101, @xexperimente, @tommaskraus, @CodeSkills, @VaclavPavek,

Hi all, I see we did a lot of iterations on Czech, I would try to get all declensions working.

Can you check this PR and examples in unit tests (is it better/worst)?

Can you give me more examples, like this:
```
4 hours, 30 minutes and 5 seconds
4 hours, 30 minutes and 5 seconds before *lunch*
4 hours, 30 minutes and 5 seconds after *lunch*
4 hours, 30 minutes and 5 seconds ago
4 hours, 30 minutes and 5 seconds from now
1 hour, 1 minute and 1 second
1 hour, 1 minute and 1 second before *lunch*
1 hour, 1 minute and 1 second after *lunch*
1 hour, 1 minute and 1 second ago
1 hour, 1 minute and 1 second from now
2 hours, 2 minutes and 2 seconds
2 hours, 2 minutes and 2 seconds before *lunch*
2 hours, 2 minutes and 2 seconds after *lunch*
2 hours, 2 minutes and 2 seconds ago
2 hours, 2 minutes and 2 seconds from now
```

Or the rules to follow.

Do we also need to use hodinami/minutami/sekundami in ago/from now/before/after sentences?

**Comment by VaclavPavek** [comment]
@kylekatarnls more examples

1 hodina, 2 - 4 hodiny, 5-24 hodin
před / before / ago : 1 hodinou, 2-24 hodinami
za / after / from now : 1 hodinu, 2-4 hodiny, 5-24 hodin

1 minuta, 2 - 4 minuty, 5-60 minut
před / before / ago : 1 minutou, 2-60 minutami
za / after / from now : 1 minutu, 2-4 minuty, 5-60 minut

1 sekunda, 2 - 4 sekundy, 5-60 sekund
před / before / ago : 1 sekundou, 2-60 sekundami
za / after / from now : 1 sekundu, 2-4 sekundy, 5-60 sekund


1 hodina, 1 minuta a 1 sekunda
1 hodina, 1 minuta a 1 sekunda před obědem
1 hodina, 1 minuta a 1 sekunda po obědě
před 1 hodinou, 1 minutou a 1 sekundou 
za 1 hodinu, 1 minutu a 1 sekundu

2 hodiny, 2 minuty a 2 sekundy
2 hodiny, 2 minuty a 2 sekundy před obědem
2 hodiny, 2 minuty a 2 sekundy po obědě
před 2 hodinami, 2 minutami a 2 sekundami
za 2 hodiny, 2 minuty a 2 sekundy

6 hodin, 30 minut a 5 sekund
6 hodin, 30 minut a 5 sekund před obědem
6 hodin, 30 minut a 5 sekund po obědě
před 6 hodinami, 30 minutami a 5 sekundami
za 6 hodin, 30 minut a 5 sekund

**Comment by kylekatarnls** [comment]
Thanks, understood the ou/ami declension, I will add it.

**Comment by kylekatarnls** [comment]
Translation updated, please have a look at unit tests:
https://github.com/briannesbitt/Carbon/pull/1741/files#diff-e59d70b94caafff409b7042f75aa853c

Gray comments are the code to execute, red lines are the old translations, green lines are the new translations.

You also can use `"nesbot/carbon": "fix-issue-1740-cs-translation",` in your **composer.json** `require` list to test new translations before it's merged. I will wait a few days, and if no one has any objection, I will release this changes in 2.19.1.

**Comment by VaclavPavek** [comment]
> Translation updated, please have a look at unit tests:
> https://github.com/briannesbitt/Carbon/pull/1741/files#diff-e59d70b94caafff409b7042f75aa853c

bad: před 2 sekundoumi
correctly: před 2 sekundami

bad: před 2 minutoumi
correctly: před 2 minutami

"ou" => před 1 hodinou / minutou / sekundou
"ami" => před 2 hodinami / minutami / sekundami

Czech is specific in declension and unfortunately it doesn't work everywhere at 100%. When I have time (about a month) so I look at it in more detail, and edit the rest ;-)

**Comment by kylekatarnls** [comment]
It was not supposed to get "oumi" as my replacement was `preg_replace('/sekundy?(?!\w)/', 'sekundami', $time)` I will check what's wrong in the replacement.

**Comment by kylekatarnls** [comment]
hodinami / minutami / sekundami fixed. I assume we now have a better situation, and so I will release this during the week. But of course you still can open issues later if you find other mistakes.

**Pull request merged**
