### PR TITLE
Minor PSR fix

### PR DESCRIPTION
**Pull request by lucasmichot**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by lucasmichot** [comment]
Please @GrahamCampbell open StyleCI to public and let's make a better PSR compliant world ;-)
:+1:

**Comment by GrahamCampbell** [comment]
> Please @GrahamCampbell open StyleCI to public and let's make a better PSR compliant world ;-)

Yeh, I am planning to open it before the end of the month. It's not at a point where I can at the moment because I keep changing the database schema, and it's nice for to have the freedom to just wipe the db and start over. I'd love some feedback on StyleCI though if you want to try it out on your own machine. :)

**Comment by lucasmichot** [comment]
Already tried ;-) but not recently. Would be glad to help anyway, will give you some feedback @GrahamCampbell

**Comment by GrahamCampbell** [comment]
If you're looking to help out, sending a pull to address either https://github.com/StyleCI/StyleCI/issues/60 or https://github.com/StyleCI/StyleCI/issues/21 would be cool. I'll get around to them at some point, but if you could do them first, it'd speed things along. :)

**Comment by lucasmichot** [comment]
OK @GrahamCampbell I will tomorrow, let's get out from this post - sorry for personnal conversation @briannesbitt

**Comment by briannesbitt** [comment]
Np !

**Pull request merged**
