### PR TITLE
Update hr.php

### PR DESCRIPTION
**Pull request by wast**
Added croatian short units.

### CODE REVIEW

**Comment by kylekatarnls** [comment]
Hi, could you please update unit tests with the actual translations:
https://github.com/wast/Carbon/blob/patch-1/tests/Localization/HrTest.php

Thanks.

**Comment by wast** [comment]
There you go.

**Comment by kylekatarnls** [comment]
Hi, thanks, can you explain when we should use nedjelja and when nedjelju? We probably need a custom handler for this or a `weekdays_standlone` list to handle both forms.

**Comment by wast** [comment]
It's like [here](https://github.com/briannesbitt/Carbon/blob/3b3a2b45a2cc0175b395c119901b828a34d46c7b/src/Carbon/Lang/hr.php) in 'nextWeek', when you use (on day) "u nedjelju" / "u srijedu", it's same for 'lastWeek' "prošlu nedjelju" / "prošlu srijedu".

I guess we can try do divide:
'weekdays' => ['nedjelju', 'ponedjeljak', 'utorak', 'srijedu', 'četvrtak', 'petak', 'subotu'],
'weekdays_standalone' => ['nedjelja', 'ponedjeljak', 'utorak', 'srijeda', 'četvrtak', 'petak', 'subota'],

**Comment by wast** [comment]
@kylekatarnls now try reverting 07e01cd

**Comment by kylekatarnls** [comment]
Much better :) Now this one for short units called via CarbonInterval: https://travis-ci.org/briannesbitt/Carbon/jobs/457051445#L701

**Comment by wast** [comment]
That should be it.

**Comment by kylekatarnls** [comment]
Thanks!

**Pull request merged**
