### PR TITLE
Add the cast fixer

### PR DESCRIPTION
**Pull request by lucasmichot**
Add another fixer

### CODE REVIEW

**Comment by briannesbitt** [comment]
Not a personal fan but ok !

**Comment by dereuromark** [comment]
Me neither :D
Casts belong to the code itself they cast.

**Comment by lucasmichot** [comment]
Well in fact I don't have any opinion on that, but all casts were separated by a space in the code but this one ;)

**Comment by dereuromark** [comment]
php-cs-fixer definitely needs a NoSpaceCastFixer as contrib one :)
But good point, so far this is consistent then now.

**Pull request merged**
