### PR TITLE
Improved Hungarian translation

### PR DESCRIPTION
**Pull request by balping**

### CODE REVIEW

**Comment by lucasmichot** [comment]
Thanks @balping  , can you also add tests for that ?
You can use `\Tests\Localization\FrTest` as a starting point

**Comment by balping** [comment]
Hi @lucasmichot 

I added unit test and I also made some new improvements

https://github.com/briannesbitt/Carbon/pull/584

**Comment by balping** [comment]
You may close this, accepting my other pull request is enough https://github.com/briannesbitt/Carbon/pull/584

**Comment by GrahamCampbell** [comment]
> You may close this, accepting my other pull request is enough #584

@balping You can press the close button. ;)

**Pull request closed without merging**
