### PR TITLE
add the isLeapDay method

### PR DESCRIPTION
**Pull request by kevinb1989**
I attempt to call this method today and it's not there. It would be nice to have.

### CODE REVIEW

**Comment by kylekatarnls** [comment]
It could be just:
```php
if ($date->format('m-d') === '02-29') {
  echo 'This is a leap day';
}
```

Which makes me believe it does need a specific method.

**Comment by kevinb1989** [comment]
@kylekatarnls I have refactored accordingly.

**Comment by kylekatarnls** [comment]
But actually even `$this->isLeapYear()` is superfluous, you cannot have `->format('m-d') === '02-29'` in any other year than a leap year.

So it's already straightforward and needs only 1 short condition to check if current day is a leap day. "leap day" is a 1:1 synonym of "February 29", and I don't think we actually need an alias. 

My other concern on that is that the need in application code to actually handle February 29th in a particular way is first an edge-case, for most of the applications, it's just a day like any other. Second, the fact that something would behave any differently on February just because it's a leap day is a sign of a sub-optimal design, and thus an `if ($date->isLeapDay())` would be a code smell.

**Comment by kylekatarnls** [comment]
Closing this as not a generic-enough need, anyone with particular behavior set on February 29th just because it's a leap day is encouraged to first challenge the rule and need for this condition, and double-check that it's not a hack that can be solved in a better way at design-level.

If the condition is still judged legit in the context application, a macro can be used to get `$date->isLeapDay()` (checking Carbon instance) and `Carbon::isLeapDay()` (checking Today) methods available using:
```php
Carbon::macro('isLeapDay', static function () {
  return self::this()->format('m-d') === '02-29';
});
```

**Pull request closed without merging**
