### PR TITLE
Translate ordinal word when parsing string

### LINKED ISSUE #2692: [Translation tool] es_ES
## Additional fixes
First => primer
Second => segundo
Third => tercer
Fourth => cuarto
Last => último

----
Currently there is no translation for Ordinal Numbers format.

Example:
`[EN_US] First Sunday of november`
`[ES_ES] Primer domingo de noviembre`

---- 
I would like to contribute to this but i don´t know where to start.

### PR DESCRIPTION
**Pull request by kylekatarnls**
Fix #2692

### CODE REVIEW

**Comment by juniorb2ss** [comment]
Why was this considered a minor change and not a bump change? e.g: breaking change reported: https://github.com/briannesbitt/Carbon/issues/2716

**Comment by kylekatarnls** [comment]
Please read https://github.com/briannesbitt/Carbon/blob/master/contributing.md#note-about-semantic-versioning-and-breaking-changes

We can't possibly guess all the usage combinations and you can see how wild is already our list of tests https://github.com/briannesbitt/Carbon/tree/master/tests (we cover quite a lot of use cases).

`Carbon::createFromLocaleFormat('d \d\e F \d\e Y', 'es' ...)` is not a widely used case else we would have way more than 1 report since it was released.

Please keep in mind this software is open-source and provided for free, it is what contributors put in it. Review and BC-finding is made in best effort by the community offering time to build features.

Now we can't possibly just revert #2693 as it would be an even harder BC.

If you can provide a fix to support `Carbon::createFromLocaleFormat('d \d\e F \d\e Y', 'es' ...)` without breaking other tests, I would gladly review it.

Thanks.

**Comment by kylekatarnls** [comment]
Fix #2719 merged

**Comment by juniorb2ss** [comment]
Thank you @kylekatarnls! I really appreciate it.

**Pull request merged**
