### PR TITLE
Set PSR-4 autoloading

### PR DESCRIPTION
**Pull request by lucasmichot**
For `/src` and `/tests`
* also separate `Carbon` and `CarbonInterval` tests into distinct folders (`tests/Carbon` & `tests/CarbonInterval`
* Let the `TestFixture` consequently be an abstract test case
* Give `MyCarbon` class its own file within a `Fixtures` directory (from `StringsTest.php` to `tests/Carbon/Fixtures/MyCarbon.php`)
* Move source files and `Lang/` folder from `src/Carbon/` to `src/`

### CODE REVIEW

**Comment by vinkla** [comment]
:+1:

**Comment by lucasmichot** [comment]
(rebased)

**Comment by lucasmichot** [comment]
(rebased)

**Comment by lucasmichot** [comment]
rebased and green @briannesbitt

**Comment by lucasmichot** [comment]
(rebased)

**Comment by briannesbitt** [comment]
Sorry.... I kept skipping over this one !

**Comment by GrahamCampbell** [comment]
This PR also affects all others too.

**Comment by GrahamCampbell** [comment]
This also will break stuff for people not using composer.

**Comment by lucasmichot** [comment]
Might be easier to check locally

**Comment by GrahamCampbell** [comment]
I'd suggest not moving the contents of "src" around until 2.x.

**Comment by briannesbitt** [comment]
Agreed.

**Comment by lucasmichot** [comment]
> This also will break stuff for people not using composer.
Not the argument I would keep IMO

**Comment by GrahamCampbell** [comment]
We should still move to PSR4, just without moving the stuff in src.

**Pull request closed without merging**
