### PR TITLE
New modifiers startOfMinute() and startOfHour()

### PR DESCRIPTION
**Pull request by ymhuang0808**
Follow PR #952 and add unit testing.

### CODE REVIEW

**Comment by Glavic** [comment]
@kylekatarnls: we could add this to milestone 1.24 ?

**Comment by kylekatarnls** [comment]
Note: this one contains same methods #928

**Comment by kylekatarnls** [comment]
Merged via #1151 (authorship given to @zaaom that did the earliest proposition in #928)

**Comment by zaaom** [comment]
@kylekatarnls thank you 👍
credits to @EGYG33K #571

**Comment by kylekatarnls** [comment]
Commit authors of #571 are "zaaom". Aren't you the author of the code?

**Comment by zaaom** [comment]
@kylekatarnls i'm no worries :)

crediting @EGYG33K as well, he contributed as well earlier: https://github.com/G33KsZone/Carbon/pulls?q=is%3Apr+is%3Aclosed

**Pull request closed without merging**
