### PR TITLE
Allows to create an instance from a \DateTimeImmutable

### PR DESCRIPTION
**Pull request by lucasmichot**
Allows to create an instance from a \DateTimeImmutable

### CODE REVIEW

**Comment by dereuromark** [comment]
Refs https://github.com/briannesbitt/Carbon/pull/233

**Comment by lucasmichot** [comment]
yeah @dereuromark I'll add datetimeinterface too

**Comment by dereuromark** [comment]
@lucasmichot Isnt that 5.5+? I don't think the Interface works BC here.

**Comment by lucasmichot** [comment]
Yeah both are  >= 5.5.0

DateTimeInterface >= 5.5.0
DateTimeImmutable >= 5.5.0

**Comment by lucasmichot** [comment]
For DateTimeImmutable it works fine, for DateTimeImmutable I'll check

**Comment by lucasmichot** [comment]
Interesting:
`PHP Fatal error:  DateTimeInterface can't be implemented by user classes`

**Pull request closed without merging**
