### PR TITLE
Added support for Urdu.

### PR DESCRIPTION
**Pull request by mehshan**
Added Urdu locale and its test case.

### CODE REVIEW

**Comment by lucasmichot** [comment]
Can you rebase your PR against master and the push force it @mehshan ?

**Comment by mehshan** [comment]
@lucasmichot I'm already using add-urdu-lang branch in a project that relies on Carbon v1.21.0. I guess, I could do another branch from master, cherry pick my commit in it and submit a new pull request. Will that work?

**Comment by lucasmichot** [comment]
In this case, can you apply https://styleci.io/analyses/XlZ0Ww ?
It won't harm your code

**Comment by lucasmichot** [comment]
NVM, style fixes can be applied later

**Comment by lucasmichot** [comment]
??

**Comment by mehshan** [comment]
Submitted a new PR #667 with master as base. Also has style fixes.

**Pull request closed without merging**
