### PR TITLE
Minor CS adjustments

### PR DESCRIPTION
**Pull request by lucasmichot**
Minor CS adjustments

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Why not enable these fixers?

**Comment by lucasmichot** [comment]
Are they not already ?

**Comment by lucasmichot** [comment]
Nvmm...

**Comment by lucasmichot** [comment]
Added `concat_without_spaces` 
No clue of the fixer to add to ensure there is a linebreak between functions, any idea @GrahamCampbell ?

**Comment by GrahamCampbell** [comment]
There is a method separation fixer. Not sure if it exists in php-cs-fixer 1.x.

**Comment by dereuromark** [comment]
I vote against concat_without_spaces. Should be concat_with_spaces IMO.

**Comment by GrahamCampbell** [comment]
concat without is more standard and is used by laravel and symfony, to name a few

**Comment by dereuromark** [comment]
Not CakePHP for example. And concat is like any other operation, `+`, ... and all those have a spacing.
It is only consistent to use one. Only because some frameworks do not follow the consistency does not make it right, though :)

**Comment by lucasmichot** [comment]
@dereuromark `concat_without_spaces` would make more sense as all of the other concatenation in the code are already spaceless.
@GrahamCampbell :+1: thx

**Pull request merged**
