### PR TITLE
Update lt.php

### PR DESCRIPTION
**Pull request by m4nt4s**
Corrected month translations.

According to Lithuanian language month translation must be _mėnesis_, not _menesis_.

### CODE REVIEW

**Comment by lucasmichot** [comment]
Can you also add tests @m4nt4s ?

**Comment by m4nt4s** [comment]
Added tests

**Comment by lucasmichot** [comment]
@m4nt4s how can a plural have tow different forms ?

**Comment by m4nt4s** [comment]
it's because of our language words declension. 

prieš 1 mėnesį.
pries 2 mėnesius.
..
..
prieš 9 mėnesius.

prieš 10 mėnesių.
prieš 11 mėnesių.
prieš 12 mėnesių.

**Comment by lucasmichot** [comment]
Then in this case, all LT translation are false and should follow the convention already used for arabic
https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/ar.php#L21 ?

**Comment by m4nt4s** [comment]
No. It's enough for now with these translations what we have.

**Comment by lucasmichot** [comment]
It's not sure it is, tests are failing on master branch because of the lituanian translations

**Comment by lucasmichot** [comment]
Should you say `prieš 21 sekundęs` or `prieš 21 sekundžių` ?

**Comment by lucasmichot** [comment]
Many tests have been added for LT

Any idea with this test is failing in master ?

```php
$d = Carbon::now()->subSeconds(21);
$scope->assertSame('prieš 21 sekundžių', $d->diffForHumans());
```

````
@@ @@
-prieš 21 sekundžių
+prieš 1 sekundę
````

**Comment by m4nt4s** [comment]
It's because in translation there is
**1 sekundę** and not **:count sekundę**

**Comment by m4nt4s** [comment]
and the same is with days.

**Comment by lucasmichot** [comment]
Could you have a look at it ?
And maybe create new PR for master ?

**Comment by m4nt4s** [comment]
It's because of numbers 21, 31, 41, 51. And the same is with years too.

**Comment by m4nt4s** [comment]
I can change the rules from 1 to :count and problem should be solved

**Comment by lucasmichot** [comment]
A global check at `lt.php` and to `\Tests\Localization\LtTest` (in master) would be great
Lithuanian numbers are quite tricky

**Comment by m4nt4s** [comment]
Ok done with tests and translations.

**Comment by lucasmichot** [comment]
Nice ! Can you rebase against master ?

**Comment by m4nt4s** [comment]
mmm. I never did that before

**Comment by lucasmichot** [comment]
Maybe starting from a new PR would be easier ?

**Comment by m4nt4s** [comment]
do I have to marge patch-2 into master branche?

**Pull request closed without merging**
