### PR TITLE
Edit language for Greenlandic

### PR DESCRIPTION
**Pull request by mashema**

### CODE REVIEW

**Comment by mashema** [comment]
Edit language for Greenlandic

**Comment by kylekatarnls** [comment]
Thanks for your help, I see the `:count` (which is replaced by the number) is sometimes after sometimes before. Can you confirm all those examples get from this new translations are in the right order?
ukioq 1
0 ukiut
ukiut 2
qaammat 1
0 qaammatit
qaammatit 2
1 ulloq
0 ullut
2 ullut
If yes, can you explain the rule?

**Comment by mashema** [comment]
I'm not a native speaker, but it's confirmed. I will get the translator to create an explanation

**Comment by kylekatarnls** [comment]
Thank you, I wanted to be sure, there was not some left-to-right issue. But I'm also curious to know how the somehow variable ordering happen :)

**Comment by Taatsiannguaq** [comment]
> Thanks for your help, I see the `:count` (which is replaced by the number) is sometimes after sometimes before. Can you confirm all those examples get from this new translations are in the right order?
> ukioq 1
> 0 ukiut
> ukiut 2
> qaammat 1
> 0 qaammatit
> qaammatit 2
> 1 ulloq
> 0 ullut
> 2 ullut
> If yes, can you explain the rule?

In greenlandic :count is complicated when it needs to be correct translated from danish and english. That is why numbers needs to be replaced by the letters and some times numbers and letters is sometimes after sometimes before. Here are some samples on correct use of dates (we dont use it now, because the formats of dates are in a hurry translated into Greenlandic and just swapped numbers before and after ":count")

2 years ago - 2 år siden - ukiut marluk matuma siorna 
12 years ago - 12 år siden - ukiut aqqaneq marluk matuma siorna
13 years ago - 13 år siden - ukiut 13-t matuma siorna
Explanation: When time is between 1 to 12, the words for numbers are used in date like: two years ago. And from 13 digits are used with "-t" at the end for each number.
This is used among date formats for years, months, weeks, days etc.

2 months ago - 2 måneder siden - qaammatit marluk matuma siorna 
11 months ago - 11 måneder siden - qaammatit aqqanillit matuma siorna

2 days ago - 2 dage siden - ullut marluk matuma siorna 
12 days ago - 12 dage siden - ullut aqqaneq marluk matuma siorna
13 days ago - 13 dage siden - ullut 13-t matuma siorna

years - år - ukiut
months - måneder - qaammatit
days - dage - ullut

The easiest way to fix this, is to disable time/date counts in Greenlandic and replaced it with "Kingullermi allanngortinneqarpoq" - "Last edited"
Example:
Technical breakdown at Kullorsuaq (Upernavik)
2 days ago - 11.09.2020 15:27

Teknisk nedbrud ved Kullorsuaq (Upernavik)
2 dage siden - 11.09.2020 15:27

Kullorsuarmi (Upernavimmi) teknikkikkut ajutoorneq
Kingullermi allanngortinneqarpoq - 11.09.2020 15:27

**Comment by kylekatarnls** [comment]
Thank you, it would be possible eventually to use number words instead of digits, but it would require to set for each unit the twelve numbers, such as: `{1}ullut "one"|{2}ullut "two"|{2}ullut "three"|...|]12,Inf]ullut :count-t` but if the digits form of the PR can be properly understood. I would rather stick to it.

**Comment by Taatsiannguaq** [comment]
> Thank you, it would be possible eventually to use number words instead of digits, but it would require to set for each unit the twelve numbers, such as: `{1}ullut "one"|{2}ullut "two"|{2}ullut "three"|...|]12,Inf]ullut :count-t` but if the digits form of the PR can be properly understood. I would rather stick to it.

Yes, as for now the digits form can be properly understand in Greenlandic, even it is not correct use of the language.

**Pull request merged**
