### PR TITLE
Allow Symfony 7

### PR DESCRIPTION
**Pull request by evertharmeling**
Tried to make the library compatible with Symfony 7

- Followed the same setup using the `Lazy` implementation already used for the `Translator` class, to handle the incompatible return types and type hinted arguments.
- Not sure how to cope with the change of `Translator::setLocale` returning `void` (throwing `\Symfony\Component\Translation\Exception\InvalidArgumentException`) instead of `bool`. As I have the feeling it's just a BC break? It's getting more and more quirky to keep supporting older versions (of Symfony). Symfony `5.4` is the lowest LTS version atm, see https://symfony.com/releases
  - For now added skipping tests when the return type is `void`

Thoughts?

### CODE REVIEW

**Comment by kylekatarnls** [comment]
Symfony 7 will be supported on Carbon 3, you can test it with
```
composer require nesbot/carbon:^3.0@dev
```

**Comment by evertharmeling** [comment]
Ah missed that, cool will do!

**Comment by VincentLanglet** [comment]
> Symfony 7 will be supported on Carbon 3, you can test it with
> 
> ```
> composer require nesbot/carbon:^3.0@dev
> ```

Hi @kylekatarnls, can't it be supported on Carbon 2 without BC break ?
This would allow to make a release now with SF 7 support to allow other open source library working on SF 7 from now (also without having to bump a new major dependencies).

Or at least could a stable release of the v3 could be done ?
This will allow other libraries to not rely on a `@dev` version.

Thanks a lot

**Comment by kylekatarnls** [comment]
Hello, version 2 is there since 2018, PHP 7.1, we're now at 2.71 minor version, and it's already a huge gap to fill to be compatible from Symfony 3.4 to 6, it's time for it to end.

Next step will be to provide adjustments in Laravel for them to be able to upgrade smoothly, then 3.0 will get a stable release.

**Comment by kylekatarnls** [comment]
v3 compatibility with Laravel is now being checked: laravel/framework#49764

If you are on Laravel or have a composer constraint in your project needed carbon v2, you can still try the v3 using:

```
composer require "nesbot/carbon:3.x-dev as 2.99"
```

Do not hesitate to give it a try, your help in testing this new version will be gratefully welcome. The more it can be tested, the faster it will reach the stable release.

**Pull request closed without merging**
