### PR TITLE
Issue 88 : modify with timezone

### PR DESCRIPTION
**Pull request by kylekatarnls**
[Issue 88 : Adding to a time provides an inconsistent result](https://github.com/briannesbitt/Carbon/issues/88)

### CODE REVIEW

**Comment by lucasmichot** [comment]
What is the status of this PR @kylekatarnls @briannesbitt ?

**Comment by kylekatarnls** [comment]
No shorter fix found

**Comment by lucasmichot** [comment]
Can you rebase this PR maybe ?

**Comment by briannesbitt** [comment]
Do you guys consider this a BC or a bug fix ?

**Comment by GrahamCampbell** [comment]
Should be closed in favour of #548.

**Pull request closed without merging**
