### PR TITLE
Re-align __set_state on DateTime method

### PR DESCRIPTION
**Pull request by kylekatarnls**

### CODE REVIEW

**Comment by NicolasDepoilly** [comment]
Thanks for reactivity and have a nice week end!

**Comment by kylekatarnls** [comment]
You're welcome

**Comment by NicolasDepoilly** [comment]
Sorry, it is still not fixed! I just tested and we have same issue

**Comment by 36864** [comment]
This was fixed on the laravel side and new releases tagged before this change was made public. Now it's defined as `array $array` in Laravel and just `$array` in Carbon.

**Comment by kylekatarnls** [comment]
The fix in Laravel was wrong. Laravel do the exact same thing as Carbon, it should not be overridden, so next step here: https://github.com/laravel/framework/pull/23464

**Comment by NicolasDepoilly** [comment]
yeah i saw the issue, wasnt able to send pull request, probably I don't have rights on your repo?

**Comment by anare** [comment]
https://github.com/laravel/framework/issues/23465

**Pull request merged**
