### PR TITLE
Small translation improvement

### PR DESCRIPTION
**Pull request by obikenoby**

### CODE REVIEW

**Comment by kylekatarnls** [comment]
Hi, in your version, `ago` and `before` produce the same translation. Please explain the differences of meaning of the previous and new translatons.

**Comment by obikenoby** [comment]
We have same word for ago and before. Primarily, I suggested change in sequence of words and in relation to this change I suggested change of wording too.

**Comment by kylekatarnls** [comment]
Hi @obikenoby I do not speak Czech myself, so I need references (texts examples in notorious sites) and precise explanation (what context for what expression), here is a compilation of reference:

|Author|Source|before|after|ago|from_now|
|--|--|--|--|--|--|
|@obikenoby|Carbon|před :time|po :time|před :time|od :time|
|@Tlapi|Carbon|:time předtím|:time později|:time nazpět|za :time|
|@CylonSK|[jenssegers/date](https://github.com/jenssegers/date)|:time předtím|:time později|před :time|za :time|
|@petrbela|[moment.js](https://github.com/moment/moment)| | |před :time|za :time|
| |Google Translate|:time předtím|:time po|před :time|:time od teď|

And Google Translate give me a declination we do not handle 2 hodiny become 2 hodinami with "ago". It would imply to write a closure in your translation file to handle this properly if it's the right way to translate it.

As you can see, it's pretty impossible to me to know who is wrong and who is right.

Maybe people in this table and previous contributors (such as @VaclavPavek) could give their opinion on this?

Also remember that time can be any unit (year, week, day, seconds) or group of units (2 hours, 23 minutes and 50 seconds).

**Comment by VaclavPavek** [comment]
The Czech language depends on the context of the sentence. Existing translations seem to me right with existing translations (year, week, day, seconds).

Personally, I would not change the current translation. There are https://carbon.nesbot.com/docs/#api-localization location change options.

My opinion is not supported by tests, only by looking at source files and one application I used to use the library (no translation problems found).

**Comment by kylekatarnls** [comment]
Hi @VaclavPavek thanks a lot for your help! I will close this for now so. But if anyone would bring new references, please feel free to comment and I will reopen the discussion.

**Pull request closed without merging**
