### PR TITLE
Allow to customize join syntax for human diff units

### PR DESCRIPTION
**Pull request by kylekatarnls**
Following #1556 suggestion, this PR allows to customize the list syntax for human diff methods output.

Yet for the CarbonInterval:
```php
$interval = CarbonInterval::create(1, 1, 0, 1, 1)->locale('en');
$interval->forHumans() // 1 year 1 month 1 day 1 hour
$interval->forHumans([
    'join' => true,
]) // 1 year, 1 month, 1 day and 1 hour
$interval->forHumans([
    'join' => ', ',
]) // 1 year, 1 month, 1 day, 1 hour
$interval->forHumans([
    'join' => [' and ', ' and also '],
]) // 1 year and 1 month and 1 day and also 1 hour
$interval->forHumans([
    'join' => function ($list) {
        return '['.implode(';', $list).']';
    },
]) // [1 year;1 month;1 day;1 hour]
```

All other parameters (syntax/short/parts/options) can be passed also as an entry of the first parameter if this parameter is an array as above.

To come: for Carbon/CarbonImmutable diffForHumans/ago/until/since/from/to

### CODE REVIEW

**Comment by kylekatarnls** [comment]
The same is now available for diffForHumans/ago/until/since/from/to in this PR:

```php
$date->diffForHumans([
    'parts' => 2,
    'join' => true,
]) // 2 days and 3 hours ago
$date->diffForHumans([
    'parts' => -1,
    'join' => true,
]) // 2 days, 3 hours and 40 minutes ago
$date->diffForHumans(Carbon::now()->addDay(), [
    'parts' => -1,
    'join' => true,
]) // 3 days, 3 hours and 40 minutes before
$date->diffForHumans([
    'other' => Carbon::now()->addDay(),
    'parts' => -1,
    'join' => true,
]) // 3 days, 3 hours and 40 minutes before
$date->diffForHumans([
    'parts' => 2,
    'join' => ', ',
]) // 2 days, 3 hours ago
$date->diffForHumans([
    'parts' => 2,
    'join' => ', ',
    'short' => true,
]) // 2d, 3h ago
$date->diffForHumans([
    'parts' => 2,
    'join' => ', ',
    'syntax' => CarbonInterface::DIFF_RELATIVE_TO_OTHER,
]) // 2 days, 3 hours before
Carbon::yesterday()->diffForHumans([
    'options' => CarbonInterface::ONE_DAY_WORDS,
]) // yesterday
Carbon::yesterday()->diffForHumans([
    'options' => 0,
]) // 1 day ago
```

**Comment by oriceon** [comment]
@kylekatarnls Yup. Is more than good. Can you also update romanian language with "și" translation list? 

Thank you for your greate work and for this nice aproach !!!

**Comment by oriceon** [comment]
@kylekatarnls when you expect new release with new changes?

**Comment by kylekatarnls** [comment]
Should be released by the end of December. But you can yet test it with: `"nesbot/carbon": "dev-master"` in your **composer.json**.

**Pull request merged**
