### PR TITLE
choose the format when transforming the date to a string

### PR DESCRIPTION
**Pull request by djug**

### CODE REVIEW

**Comment by lucasmichot** [comment]
@djug , it's looking a bit hacky, because you could then do `$carbon->toDateString('H')`.
This function, supposed to represent a date, would return the hour

**Comment by lucasmichot** [comment]
Ping @djug

**Comment by djug** [comment]
@lucasmichot  I don't see any problem with that

**Comment by lucasmichot** [comment]
There is no tests

**Comment by briannesbitt** [comment]
I don't see the need for this.  Just use the format() method directly if
you need something specific.

If you need something specific often then you can use
Carbon::setToStringFormat().

**Pull request closed without merging**
