### PR TITLE
Incorrect suffix used

### PR DESCRIPTION
**Pull request by swarakaka**
Because the Kurdish (Central) suffix is [ckb](https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/ckb.php), this suffix is used for Kurdish (Kurmanji). Please remove it.

### CODE REVIEW

**Comment by swarakaka** [comment]
I accidentally deleted the repository.

**Comment by swarakaka** [comment]
Please reopen it again, I accidentally deleted my PR.

**Comment by kylekatarnls** [comment]
This is indeed an error copied from https://github.com/moment/moment/blob/develop/locale/ku.js

But I can see CLDR is providing correct data, I will implement Kurdish (Kurmanji) language properly.

**Comment by kylekatarnls** [comment]
Closing this in favor of #2646

**Pull request closed without merging**
