### PR TITLE
Allow 2.6 and beyond.

### PR DESCRIPTION
**Pull request by peshi**
Allow Symfony 2.6+

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
We should probably allow `~3.0` too.

**Comment by GrahamCampbell** [comment]
`"symfony/translation": "~2.6|~3.0"`

**Comment by peshi** [comment]
Good point, added.

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by taylorotwell** [comment]
:+1:

**Comment by briannesbitt** [comment]
Haven't looked yet, but any idea if there are any BC's in the translation component 3.x vs 2.6 ?

**Comment by peshi** [comment]
The Translator::setFallbackLocale() method has been removed in favor of Translator::setFallbackLocales()

Other then that I can't see any issue.

**Comment by briannesbitt** [comment]
going with https://github.com/briannesbitt/Carbon/pull/355

**Comment by peshi** [comment]
rofl, 3 PR's later..

**Pull request closed without merging**
