### PR TITLE
Fix #1790 diffInSeconds/Microseconds calculation

### LINKED ISSUE #1790: Unexpected diffInSeconds/Microseconds output
Hello,

I encountered an issue with the following code:

```php
$d1 = Carbon::parse('2019-06-15 12:34:56.123456');
$d2 = Carbon::parse('2019-06-16 12:34:56.123455');

echo $d2->diffInSeconds($d1);
```

Carbon version: **2.20.0**

Laravel version: **5.8.28**

PHP version: **7.3.1**

I expected to get:

```
86399
```

But I actually get:

```
172799
```
(1 day added)

Thanks!

### PR DESCRIPTION
**Pull request by jxlwqq**

### CODE REVIEW

**Comment by kylekatarnls** [comment]
This change seems to break tests in PHP 7.2.12
https://travis-ci.org/briannesbitt/Carbon/jobs/558758994

days/d switch is inherited from PHP 5 compatibility of Carbon 1, maybe `d` could be used safely with the compatibility range of Carbon 2 but we have to check it wisely.

**Comment by jxlwqq** [comment]
> I added tests, please confirm it matches the case you want to fix.

yes, thank you.

**Comment by bohehe** [comment]
excellent😺

**Comment by kylekatarnls** [comment]
To do:
- handle [bug 77007](https://bugs.php.net/bug.php?id=77007) until PHP 7.2.12
- handle [regression 77097](https://bugs.php.net/bug.php?id=77097) since PHP 7.2.12 and until PHP 7.2.14

**Comment by kylekatarnls** [comment]
Will be fixed in 2.21.1

**Pull request merged**
