### PR TITLE
Rename the Brazilian Portuguese locale code

### PR DESCRIPTION
**Pull request by limatheus**
Rename the Brazilian Portuguese locale code to pt-BR instead pt_BR.

### CODE REVIEW

**Comment by dereuromark** [comment]
What about zh_*?
I am pretty sure the underscore is the convention here.

**Comment by limatheus** [comment]
In many places is used pt-BR instead pt_BR, but if the undescore convention here, OK.
I'm closing this pull request now.

**Comment by dereuromark** [comment]
That was more like an assumption. You should let the package maintainers decide on it.

**Comment by limatheus** [comment]
What I do? 
I should keep this pull request open?

**Comment by lucasmichot** [comment]
@limatheus this is on purpose : see https://github.com/briannesbitt/Carbon/pull/516

**Comment by limatheus** [comment]
Many other packages uses pt-BR instead pt_BR.
https://github.com/caouecs/Laravel-lang/tree/master/pt-BR
https://github.com/ARCANEDEV/LogViewer/tree/master/resources/lang/pt-BR

**Comment by lucasmichot** [comment]
We prefer to stick to Linux locale format: https://wiki.archlinux.org/index.php/Locale
And if you ever had your own external overriden locale, it will anyway be loaded.

So what is the added value ?

**Comment by limatheus** [comment]
Understood :+1:

**Comment by lucasmichot** [comment]
I'm :-1: for this one 

If you wish to contribute, we would love a PR with tests for Brazilian Portuguese (if you are a native speaker). Feel free to copy and paste `\Tests\Localization\FrTest` as a starting point @limatheus

**Pull request closed without merging**
