### PR TITLE
Fix mistype

### PR DESCRIPTION
**Pull request by riccai**
Just small mistype fix

### CODE REVIEW

**Comment by lucasmichot** [comment]
Thanks @riccai !
Are you a native Lithuanian speaker ? It would be awesome if you could also provide a test for this language

You can copy and paste `\Tests\Localization\FrTest` as a starting point

**Comment by riccai** [comment]
@lucasmichot yes I am, I will take a look on that. Today I found something weird, maybe a bug.
For example I have time on database 2016-01-27 21:18:49, current server time is 2016-01-28 18:32:00 and when I use $classified->updated_at->diffForHumans() it returns "prieš 1 valandą", but it should be "prieš 21 valandą". When I switch language to English everything works fine.

**Comment by lucasmichot** [comment]
Thanks you !

**Comment by lucasmichot** [comment]
@riccai what is the difference between mėnesius and mėnesių for the plural of minutes?
Is mėnesius only used under a specific count ?

**Comment by keksas** [comment]
@lucasmichot it's difficult to explain the difference.

Both words are only used for plural (and they mean Months not minutes as you stated).

`mėnesių` is plural genitive and `mėnesius` is plural accusative.

Sentence tense defines how they are used:

"Po 9 mėnesių" -> After nine months
"Prieš 2 mėnesius" -> Two months ago

**Comment by lucasmichot** [comment]
OK I see, maybe check for https://github.com/balping/Carbon/blob/master/src/Carbon/Lang/hu.php in #584 from @balping
He's covering lots of different use cases in Magyar

**Comment by lucasmichot** [comment]
Yeah, I've just checked, Magyar do have cases too (up to 18... !!!!)

**Comment by lucasmichot** [comment]
See @balping very complete test too : https://github.com/balping/Carbon/blob/master/tests/Localization/HuTest.php

**Pull request merged**
