### PR TITLE
Add Pashto language

### PR DESCRIPTION
**Pull request by mnrafg**
Pashto is one of Afghanistan's official languages.

### CODE REVIEW

**Comment by Horat1us** [comment]
Tests?

**Comment by Pashtunzoy** [comment]
@mnrafg I have created tests for you so reply back so I can fork your forked repo and push my already tested code. Otherwise, @Horat1us I can create a new pull request if @mnrafg doesn't reply. So is that cool?

**Comment by mnrafg** [comment]
@Pashtunzoy thanks for creating the tests, as I was busy and was not able inspect the issue further, so now you can go forward thank you again.

**Comment by Pashtunzoy** [comment]
@mnrafg Don't close this issue. The pull request hasn't been merged yet. Close it after they have been approved by the repo admin.

**Comment by mnrafg** [comment]
There were some issues with this PR so I started a new one by the following link: [https://github.com/briannesbitt/Carbon/pull/967](https://github.com/briannesbitt/Carbon/pull/967).

**Pull request closed without merging**
