### PR TITLE
Mute codecov PR comments

### PR DESCRIPTION
**Pull request by lucasmichot**
Mute codecov PR comments

### CODE REVIEW

**Comment by shooka** [comment]
The same files are failing in #673 😄 

Something must have changed in StyleCI.

**Comment by lucasmichot** [comment]
> The same files are failing in #673

Indeed - I suppose @briannesbitt will make only one global style fix after many PR have been merged

**Comment by shooka** [comment]
I was thinking the same thing - If all of us changed it, we would get a lot of merge conflicts 😄

**Comment by briannesbitt** [comment]
Yes, working the PRs and will update at the end ;)

**Comment by lucasmichot** [comment]
@briannesbitt I feel this PR could be merged now

**Pull request merged**
