### PR TITLE
Add Syfmony 4.0 constraint

### PR DESCRIPTION
**Pull request by GawainLynch**
Symfony 4 is about to land :tada: :champagne:, and the breaking changes to the Translate component aren't relevant to Carbon … and your wonderful little library is used pretty heavily out there. :heart: 

So here we go :smile: 

Closes: #1049

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
👍

**Comment by matt-usurp** [comment]
Any movement here? 
Can we get a merge and release so people can upgrade to Symfony 4 tomorrow?

**Comment by Aerendir** [comment]
Any news here?

**Comment by mdwheele** [comment]
Will this be merged any time soon?

**Comment by GawainLynch** [comment]
@briannesbitt @lucasmichot - I don't suppose we could get a holiday present for all the Carbon fans out there in the form of a merge+tag? :pray:

**Comment by mdeboer** [comment]
Please merge this, could really use it! 👍

**Comment by deviouspk** [comment]
Fork & make your own. This repo hasn't been updated in almost a year..

**Comment by GawainLynch** [comment]
> Fork & make your own. This repo hasn't been updated in almost a year..

Yep, and today is the day that it kicks into motion — https://github.com/CarbonDate/Carbon

I've merged this, plus some more translations and cleaned up tests & PHPStan failures (now up to level 6 coverage in the stable branch) and tagged 1.23.0 … fully supporting Symfony 4.

**Comment by mdeboer** [comment]
@GawainLynch cheers! I'll delete my fork and use yours instead.

**Comment by dereuromark** [comment]
If you rather want to use the modern PHP7 features, I recommend the successor https://github.com/cakephp/chronos

**Pull request merged**
