### PR TITLE
Unify data providers method names

### PR DESCRIPTION
**Pull request by lucasmichot**
This PR ensure that all tests data providers are prefixed with `provider`.
This PR also enforces consistency and ensures that all all the methods are fully-qualified.

### CODE REVIEW

**Comment by lucasmichot** [comment]
> Another suggestion maybe for the future: make data provider method `static`. They're effectively this, because they are evaluated upfront before the test suite is ran.

Absolutely @mfn
Probably part of another PR

**Comment by kylekatarnls** [comment]
I would be OK to harmonize but it's the first time I see "provider" as a prefix. It makes it grammatically wrong for instance for "providerLocales" I would prefer a verb such as "provideLocales" or a suffix "localesProvider" so we can get an English readable method name.

**Comment by mfn** [comment]
I found this tweet https://twitter.com/rectorphp/status/1169171714510602240?lang=en which suggests

> provideDataFor

and, unclear from just the tweet, I assume the test name (I guess with creative freedom if a single dataProvider is used for multiple different tests).

In private projects I've seen just `public static function dataFor<NameOfTestMethod>`; sweet'n'short (the prefix).

HTH

**Comment by lucasmichot** [comment]
I like `dataFor` a lot

**Comment by kylekatarnls** [comment]
👍 OK for `dataFor`

**Review by kylekatarnls — APPROVED** [review]

**Pull request merged**
