### PR TITLE
Added Translation for Gujarati language

### PR DESCRIPTION
**Pull request by hiteshchavda**
– Gujarati language is one of the many languages spoken in India

### CODE REVIEW

**Comment by kylekatarnls** [comment]
Hi, thanks a lot!

Could you please add unit tests for this language th same way than: https://github.com/briannesbitt/Carbon/blob/master/tests/Localization/EnTest.php

If this language does not have short/abbreviated form, you can omit testDiffForHumansUsingShortUnits.

This will guarantee the expected formatted sentences produced.

Thanks.

**Comment by hiteshchavda** [comment]
Will add by end of this week 👍

**Comment by kylekatarnls** [comment]
Hi, do you need any help?

**Comment by kylekatarnls** [comment]
Will be merged via #1211

**Pull request closed without merging**
