### PR TITLE
Fix typo in zh_TW

### PR DESCRIPTION
**Pull request by jyhsu2000**
`week` in Traditional Chinese is `週`, not `周`.

### CODE REVIEW

**Comment by anze** [comment]
fix tests please

**Comment by GawainLynch** [comment]
​Owing to the apparently "unmaintained" status of this project (last official update was Februrary 2017), a small group have forked this project, and merged this pull request.
​​
You can safely update to the new project by changing `nesbot/carbon` to `carbondate/carbon` in your project's `composer.json` file.

The new home for the project is https://github.com/CarbonDate/Carbon and we welcome continuing engagement from the open source community.

Please also note that Carbon owes its very existence to Brian Nesbitt's work, and for that, we are eternally grateful.

**Comment by Glavic** [comment]
@jyhsu2000: can you rebase? TY

**Comment by kylekatarnls** [comment]
I just re-run the tests to check if it's aligned, but rebase is not necessarily needed here.

**Comment by kylekatarnls** [comment]
Hum, in fact the zh_TW test is missing. I will check how we could have a coverage constraint for i18n.

**Pull request merged**
