### PR TITLE
Update pt_BR.php shorter from_now

### PR DESCRIPTION
**Pull request by swalker2**
It means the same but is shorter

### CODE REVIEW

**Comment by lucasmichot** [comment]
Can you also tests for that ?

**Comment by swalker2** [comment]
Sure! I'm not familiar with tests, but I will try to do it this weekend. I will try to fix this Travis CI failures also.

**Comment by swalker2** [comment]
All done but I cant handle the lituan test errors...

**Comment by lucasmichot** [comment]
Can you reverse `tests/Carbon/AddTest.php` ?
This is already fixed in #696

**Comment by swalker2** [comment]
I'm not sure how to do it, I've changed the file throught the site and didn't find a "reverse" option here, if you want me to submit another merge request I can do it.
Just started using version control, sorry!

**Pull request closed without merging**
