### PR TITLE
[i18n]Update Occitan: + format, +calendar, ...

### PR DESCRIPTION
**Pull request by Quenty31**
I used the FR and CA files to figure this out, I hope it's okay

### CODE REVIEW

**Comment by kylekatarnls** [comment]
Hi, thanks a lot for those translations.

Please update unit tests:
https://github.com/Quenty31/Carbon/blob/master/tests/Localization/OcTest.php

This way you will ensure the result is what you expect with precise use cases.

From what I see, used keys and meaning seems right.

**Comment by Quenty31** [comment]
I have to update from line 20 to 76 then?

**Comment by kylekatarnls** [comment]
Indeed, lines after 76 should not change as not linked to calendar-related translations.

I'm preparing a guide for contributors: https://github.com/briannesbitt/Carbon/blob/390a19dffadcd167be96ca4173be3ebf4e8d4218/contributing.md#code-contributions

It might help you to run unit tests locally. The same tests Travis CI run can be ran on your local machine.

Basically, you need to get Git, PHP and composer, then update Carbon dependencies using composer then run `./vendor/bin/phpunit`

Then it's required to get all tests to pass. A unit test should be changed only if the expected result is obviously wrong (that's the case for tests of translations marked as incomplete in the following table: https://carbon.nesbot.com/docs/#supported-locales)

For example this test failed because `Tomorrow` has been fixed by your PR and should be `Deman a`.

So:
```php
// Carbon::parse('2018-01-04 00:00:00')->addDays(1)->calendar(Carbon::parse('2018-01-04 00:00:00'))
'Tomorrow at 12:00 AM',
```
Should become:
```php
// Carbon::parse('2018-01-04 00:00:00')->addDays(1)->calendar(Carbon::parse('2018-01-04 00:00:00'))
'Deman a 12:00',
```
And unit test will run `Carbon::parse('2018-01-04 00:00:00')->locale('oc')->addDays(1)->calendar(Carbon::parse('2018-01-04 00:00:00'))` and check if it actually matches.

Avoid copy-paste, because if there is a mistake in sources and you copy it to tests, it will make the test pass despite the error. So you should first change unit tests without considering the actual output, then if you still have unit tests failures, be sure it's really the test that is wrong and not the translation.

**Comment by kylekatarnls** [comment]
Hi @Quenty31 any new on this? If you have any doubt, feel free to ask.

**Comment by Quenty31** [comment]
Hello @kylekatarnls ! I'll try to change the test file, but the thing is I don't know how to add a file to my PR =/
I'm using the web interface..

**Comment by kylekatarnls** [comment]
As you make this PR with the `master` branch of your fork, I guess if you edit the file https://github.com/Quenty31/Carbon/blob/master/tests/Localization/OcTest.php then commit on master, it will be added to the PR.

**Comment by kylekatarnls** [comment]
You would probably be more confortable with a local development environment, you can check our new contribution guide to see how to get it: https://github.com/briannesbitt/Carbon/blob/master/contributing.md#code-contributions

**Comment by kylekatarnls** [comment]
Sorry I made a mistake, `12:00 AM` is midnight, not midday. Ahhh... AM/PM, how could someone find this more convenient than the 0 to 23 hour representation? 😄

**Comment by Quenty31** [comment]
I'm wondering too xD
Je m'y remets !

**Comment by kylekatarnls** [comment]
Hi, days are lowercase by default, it get an first letter in uppercase only if they are always this way even in the middle of a sentence (german, english).

**Comment by Quenty31** [comment]
so for the tests I have to put them in lowercase even if they are at the beginning?

**Comment by kylekatarnls** [comment]
They are not the beginning. When running `calendar` method, how Carbon could possibly know if this string will go to the beginning of a sentence or not? When starting a sentence with a language with uppercase as first letter, the developer will explicitly call `ucfirst`. What `calendar` returns does not have to assume this will be a sentence beginning, it has to be correct regarding the language (if "dimenge", is lowercase in the dictionary, then it should be in the language file and unit tests).

**Comment by kylekatarnls** [comment]
I checked, it's lowercase in Occitan. I will change them.

**Comment by kylekatarnls** [comment]
I realize it's not consistent with Today/Yesterday/Tomorrow, we should consider lowercase also those words in latin languages. I will investigate the subject.

**Comment by kylekatarnls** [comment]
Moment has the same inconsistency: "Demain", "Aujourd'hui", "Hier", "lundi", "mardi"...
https://github.com/moment/moment/blob/develop/locale/fr.js

It feels wrong and even in English, days should begin with an uppercase but "today", "tomorrow" and "yesterday" have no reason to start with an uppercase.

Change it now could have unexpected results for some users.

**Comment by Quenty31** [comment]
Woah merci ! That's a lot of changes! Thanks a lot!

**Comment by kylekatarnls** [comment]
I made some mistakes and revert them.

**Pull request merged**
