### PR TITLE
Macro feature for Carbon.

### PR DESCRIPTION
**Pull request by lucasmichot**
Enable macros for Carbon.
Inspired by Laravel macro system.

---

Possible solution for #606 from @garygreen

### CODE REVIEW

**Comment by briannesbitt** [comment]
Kinda cool.  I am not a huge fan of black magic though...  same as a subclass.

**Comment by GrahamCampbell** [comment]
I don't think this is needed. Should be closed IMO.

**Comment by GrahamCampbell** [comment]
Laravel's macro system has a very specific use case.

**Comment by BrandonSurowiec** [comment]
Having macros would be really useful for adding helper functions to Carbon. Like one that can convert a Carbon instance to use the user's local time for instance. It's kind of hard to extend Carbon with a subclass in Laravel when the Model auto resolves dates to a Carbon instance. I'm a big fan of this PR.

**Comment by BrandonSurowiec** [comment]
@lucasmichot Any chance of this being revisited?

**Comment by GrahamCampbell** [comment]
Still a big :-1: from me.

**Comment by lucasmichot** [comment]
See https://github.com/laravel/framework/pull/19771 for Laravel users

**Comment by BrandonSurowiec** [comment]
@lucasmichot Thank you!

**Comment by browner12** [comment]
@GrahamCampbell could you explain a little bit what your concerns are?  At first glance this kinda seems like a cool thing for packages where it is difficult to subclass.

**Comment by kylekatarnls** [comment]
Hi. It's an anti-pattern only according the pattern you use in your app. And I don't see the difference with other macro functions in Laravel. What about letting the user decide to use it or not?

**Pull request closed without merging**
