### PR TITLE
Rename test file

### PR DESCRIPTION
**Pull request by max-kovpak**

### CODE REVIEW

**Comment by kylekatarnls** [comment]
Hi, for PHP 5.3 compatibility and consistency, please use annotations for exceptions like this:

https://github.com/briannesbitt/Carbon/blob/master/tests/Carbon/MacroTest.php#L161

**Comment by max-kovpak** [comment]
@kylekatarnls remove this line `$this->expectException(\InvalidArgumentException::class);` or not?

**Comment by kylekatarnls** [comment]
Yes, the annotation `@expectedException` replaces it. And the annotation `@expectedExceptionMessage` allow to specify the message, this way, you're sure you did not match an other exception of the same type.

**Comment by kylekatarnls** [comment]
Thanks.

**Pull request merged**
