### PR TITLE
Use namespaced TestCase

### PR DESCRIPTION
**Pull request by MarioBlazek**

### CODE REVIEW

**Comment by Glavic** [comment]
@MarioBlazek: can you please rebase? TY

**Comment by MarioBlazek** [comment]
@Glavic rebased.

**Comment by Glavic** [comment]
Should we add latest 4.8.x version to composer? `"phpunit/phpunit": "^4.8 || ^5.7"`

**Comment by kylekatarnls** [comment]
Yes we should it enable the namespaced classe. And this class "prepare" the v6.

**Comment by kylekatarnls** [comment]
Then, phpunit is a dev tool, allowing ^4.8 is only there to run tests on 5.3, but we can use PHPUnit version as height as our PHP compatibility range allow us. It has no impact on the final package.

**Comment by kylekatarnls** [comment]
Thanks. Sorry for the delay.

**Pull request merged**
