### PR TITLE
[Issue #32] diffForHumans for differend locales

### PR DESCRIPTION
**Pull request by kylekatarnls**
Hello,
Here is ma suggestion for the [issue #32](https://github.com/briannesbitt/Carbon/issues/32).

### CODE REVIEW

**Comment by erayaydin** [comment]
approve please :+1:

**Comment by kylekatarnls** [comment]
Thx guys for your support. Please @briannesbitt, tell us about your opinion and how we can help to internationalize Carbon ASAP.

**Comment by dimsav** [comment]
+1 for this feature

**Comment by briannesbitt** [comment]
As is, from my understanding, this won't support languages with more complicated pluralization like Russian.  (and it has no tests!)

**Comment by briannesbitt** [comment]
Going to close this one off for lack of support for other languages and no tests.

See current proposed implementation https://github.com/briannesbitt/Carbon/tree/localized

**Pull request closed without merging**
