### PR TITLE
PHP-CS-Fixer is unneeded and will just conflict with StyleCI

### PR DESCRIPTION
**Pull request by GrahamCampbell**
One of StyleCI's key goals is to eliminate messing about with local cs dev tools.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Also, PHP-CS-Fixer may yield different results to StyleCI meaning you just keep going backwards and forwards with cs fixes.

**Comment by lucasmichot** [comment]
I disagree, this repository uses Travis-CI, does not mean we should not test locally too

**Comment by jbrooksuk** [comment]
@lucasmichot the point of StyleCI is not to need to fix your code locally as it's fixed at the PR level.

**Comment by lucasmichot** [comment]
@jbrooksuk yes I know. 
This repository is the perfect example of relying on php-cs-fixer AND styleci.
People were fixing StyleCI errors and thus many conflicts occured.

I've already had this talk with Graham before, and we disagree on this point.

I feel the reason why projects such as laravel/framework still provides php-cs-fixer support are mostly the same as the ones I give.

**Comment by kylekatarnls** [comment]
My two cents: do StyleCI use php-cs-fixer? Else they can check different style rules and do not replace each other. Another point is: with a local check you can work offline and push directly a cleaner code before waiting the remote check to be complete.

**Comment by jbrooksuk** [comment]
As Graham said though, there are issues with supporting both:

1. PHP-CS-Fixer does one thing, StyleCI does another. You can't have them both simply because they'll spend time fixing each others fixes.
2. StyleCI takes care of any syntax issues for you, the whole point is that you don't need to worry about that.

**Comment by GrahamCampbell** [comment]
> do StyleCI use php-cs-fixer

Not exactly, no. The output is not the same as php-cs-fixer 1.11.x.

**Comment by GrahamCampbell** [comment]
> My two cents: do StyleCI use php-cs-fixer? 

Not exactly, no. The output is not the same.

**Pull request closed without merging**
