### PR TITLE
Update Carbon.php

### PR DESCRIPTION
**Pull request by angelomaragna**
I think it's easy for non english people to call addYear instead of addYears.
In my case, I wrongly wrote addYear(2). 

if you call function addYear(2) actually adds one year. 

I think it should raise an exception or better, work as an alias for addYears.

It is right addYear() to add one year.
It is wrong addYear(45) to add one year.

### CODE REVIEW

**Comment by briannesbitt** [comment]
I agree with you.

**Comment by billmn** [comment]
Agree

Now it's important to not introduce breaking changes and fix tests.

**Comment by briannesbitt** [comment]
The failing tests were unrelated.

**Comment by briannesbitt** [comment]
Errr...  `return $this->addWeeks($value = 1);` this looks wrong !

**Comment by briannesbitt** [comment]
... wow... and default params should be "1" not "-1"... missed it but this implementation its very wrong.

**Comment by angelomaragna** [comment]
I agree, sub -1 should add and it is wrong. I am sorry for the 
$this->addWeeks($value = 1);
it is not wrong, it is incredibly wrong. I will compel myself to the good practice of writing tests :(

Sorry again.

**Comment by briannesbitt** [comment]
Thanks.  I thought the failed tests were unrelated at first glance but alas they weren't.  Seemed like an easy feature on the surface, but tests testing the new feature is always a good idea.

**Pull request merged**
