### PR TITLE
Feature/psr2

### PR DESCRIPTION
**Pull request by lucasmichot**
- Add PHP-CS-Fixer definition file (might be worth to add it to the contribution file)
- Add .styleci.yml file for using free http://styleci.io by @GrahamCampbell 
- Fix code using PSR2 presets

---

@briannesbitt feel free to add other fixers to `.php_cs` and `.style.yml` files: https://github.com/FriendsOfPHP/PHP-CS-Fixer

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by lucasmichot** [comment]
Would be valuable to add the StyleCi badge to the readme too but only you @briannesbitt can do that

**Comment by briannesbitt** [comment]
Merged and badge added

**Comment by lucasmichot** [comment]
:+1:

**Pull request merged**
